server: 
  port: 3344   
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lotus0932/microservicecloud.git #GitHub上面的git仓库名字