server: 
  port: 9527

spring: 
  application:
    name: microservicecloud-zuul-gateway
    
zuul: 
  prefix: /cy  #http://localhost:9527/cy/mydept/dept/get/1
  ignored-services: "*"
  routes: 
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 

info:
  app.name: cy-microcloud
  company.name: cy
  build.artifactId: $project.artifactId$
  build.version: $project.version$
